def escape_special_char(text):
    text.replace("&", "&amp;")
    
    text.replace("Á", "&Aacute;")
    text.replace("á", "&aacute;")
    text.replace("Â", "&Acirc;")
    text.replace("â", "&acirc;")
    text.replace("À", "&Agrave;")
    text.replace("à", "&agrave;")
    text.replace("Å", "&Aring;")
    text.replace("å", "&aring;")
    text.replace("Ã", "&Atilde;")
    text.replace("ã", "&atilde;")
    text.replace("Ä", "&Auml;")
    text.replace("ä", "&auml;")
    text.replace("Æ", "&AElig;")
    text.replace("æ", "&aelig;")

    text.replace("É", "&Eacute;")
    text.replace("é", "&eacute;")
    text.replace("Ê", "&Ecirc;")
    text.replace("ê", "&ecirc;")
    text.replace("È", "&Egrave;")
    text.replace("è", "&egrave;")
    text.replace("Ẽ", "&Etilde;")
    text.replace("ẽ", "&etilde;")
    text.replace("Ë", "&Euml;")
    text.replace("ë", "&euml;")
    text.replace("Ð", "&ETH;")
    text.replace("ð", "&eth;")
        
    text.replace("Í", "&Iacute;")
    text.replace("í", "&iacute;")
    text.replace("Î", "&Icirc;")
    text.replace("î", "&icirc;")
    text.replace("Ì", "&Igrave;")
    text.replace("ì", "&igrave;")
    text.replace("Ï", "&Iuml;")
    text.replace("ï", "&iuml;")

    text.replace("Ó", "&Oacute;")
    text.replace("ó", "&oacute;")
    text.replace("Ô", "&Ocirc;")
    text.replace("ô", "&ocirc;")
    text.replace("Ò", "&Ograve;")
    text.replace("ò", "&ograve;")
    text.replace("Ø", "&Oslash;")
    text.replace("ø", "&oslash;")
    text.replace("Õ", "&Otilde;")
    text.replace("õ", "&otilde;")
    text.replace("Ö", "&Ouml;")
    text.replace("ö", "&ouml;")
        
    text.replace("Ú", "&Uacute;")
    text.replace("ú", "&uacute;")
    text.replace("Û", "&Ucirc;")
    text.replace("û", "&ucirc;")
    text.replace("Ù", "&Ugrave;")
    text.replace("ù", "&ugrave;")
    text.replace("Ü", "&Uuml;")
    text.replace("ü", "&uuml;")

    text.replace("Ç", "&Ccedil;")
    text.replace("ç", "&ccedil;")

    text.replace("Ñ", "&Ntilde;")
    text.replace("ñ", "&ntilde;")

    text.replace("<", "&lt;")
    text.replace(">", "&gt;")
    text.replace('"', "&quot;")
    text.replace("®", "&reg;")
    text.replace("©", "&copy;")

    text.replace("Ý", "&Yacute;")
    text.replace("ý", "&yacute;")

    text.replace("Þ", "&THORN;")
    text.replace("þ", "&thorn;")

    text.replace("ß", "&szlig;")

    return text